//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BhModule.Lang5 {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MapZH {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MapZH() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BhModule.Lang5.MapZH", typeof(MapZH).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 [{&quot;i&quot;:&quot;专&quot;,&quot;o&quot;:&quot;專&quot;},{&quot;i&quot;:&quot;业&quot;,&quot;o&quot;:&quot;業&quot;},{&quot;i&quot;:&quot;丛&quot;,&quot;o&quot;:&quot;叢&quot;},{&quot;i&quot;:&quot;东&quot;,&quot;o&quot;:&quot;東&quot;},{&quot;i&quot;:&quot;丝&quot;,&quot;o&quot;:&quot;絲&quot;},{&quot;i&quot;:&quot;丢&quot;,&quot;o&quot;:&quot;丟&quot;},{&quot;i&quot;:&quot;两&quot;,&quot;o&quot;:&quot;兩&quot;},{&quot;i&quot;:&quot;严&quot;,&quot;o&quot;:&quot;嚴&quot;},{&quot;i&quot;:&quot;丧&quot;,&quot;o&quot;:&quot;喪&quot;},{&quot;i&quot;:&quot;个&quot;,&quot;o&quot;:&quot;個&quot;},{&quot;i&quot;:&quot;临&quot;,&quot;o&quot;:&quot;臨&quot;},{&quot;i&quot;:&quot;丽&quot;,&quot;o&quot;:&quot;麗&quot;},{&quot;i&quot;:&quot;举&quot;,&quot;o&quot;:&quot;舉&quot;},{&quot;i&quot;:&quot;义&quot;,&quot;o&quot;:&quot;義&quot;},{&quot;i&quot;:&quot;乌&quot;,&quot;o&quot;:&quot;烏&quot;},{&quot;i&quot;:&quot;乐&quot;,&quot;o&quot;:&quot;樂&quot;},{&quot;i&quot;:&quot;乔&quot;,&quot;o&quot;:&quot;喬&quot;},{&quot;i&quot;:&quot;习&quot;,&quot... 的當地語系化字串。
        /// </summary>
        internal static string text {
            get {
                return ResourceManager.GetString("text", resourceCulture);
            }
        }
    }
}
